language: c
sudo: required
dist: trusty
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsdl2-dev graphviz
  - mkdir tmp
  - cd tmp
  - curl https://vulkan.lunarg.com/pub/sdks/linux/latest -L -o vulkan.run
  - chmod +x vulkan.run
  - ./vulkan.run
  - export VULKAN_SDK=$(pwd)/VulkanSDK/*/x86_64
  - cd ..
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$CMAKE_BUILD_TYPE -DDEV_BUILD=$DEV_BUILD ..
  - make
  - ctest --output-on-failure
env:
  - CMAKE_BUILD_TYPE=Debug DEV_BUILD=ON
  - CMAKE_BUILD_TYPE=Debug DEV_BUILD=OFF
  - CMAKE_BUILD_TYPE=Release DEV_BUILD=ON
  - CMAKE_BUILD_TYPE=Release DEV_BUILD=OFF
